import { Inter } from 'next/font/google'
import '@/app/globals.css'
import ApplicantHeader from '../components/ApplicantHeader'
// test
const inter = Inter({ subsets: ['latin'] })

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApplicantHeader />
        {children}
      </body>
    </html>
  )
}